create table data_barang (
	id_barang INT,
	nama_barang VARCHAR(50),
	kategori VARCHAR(50),
	harga INT
);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (1, 'RX-7', 'Jewelery', 308142);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (2, 'Ion', 'Baby', 463017);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (3, 'D350', 'Beauty', 747747);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (4, 'Cutlass Supreme', 'Toys', 649201);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (5, 'Fusion', 'Books', 775625);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (6, 'Familia', 'Outdoors', 364950);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (7, 'Cabriolet', 'Home', 152590);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (8, 'IS-F', 'Garden', 432723);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (9, 'Skyhawk', 'Electronics', 676926);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (10, 'CL-Class', 'Clothing', 78052);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (11, 'Cutlass Supreme', 'Beauty', 864265);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (12, 'S10', 'Computers', 38809);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (13, 'Sportvan G20', 'Shoes', 695642);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (14, 'C30', 'Sports', 938970);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (15, 'Eurovan', 'Home', 164359);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (16, 'CTS-V', 'Music', 612182);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (17, 'Expedition', 'Books', 448560);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (18, '8 Series', 'Industrial', 67151);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (19, 'CL65 AMG', 'Jewelery', 803629);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (20, 'Escort', 'Sports', 404309);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (21, 'A3', 'Kids', 948354);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (22, '400E', 'Movies', 391147);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (23, 'Impreza', 'Tools', 474160);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (24, 'LTD', 'Home', 941172);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (25, '6 Series', 'Tools', 624076);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (26, 'Yukon', 'Outdoors', 282842);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (27, 'Golf', 'Games', 820031);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (28, 'Pathfinder', 'Health', 905959);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (29, 'Quantum', 'Health', 151481);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (30, 'Intrepid', 'Automotive', 838623);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (31, 'RL', 'Shoes', 940309);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (32, 'S-Series', 'Home', 408871);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (33, 'SL-Class', 'Electronics', 493239);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (34, '5000S', 'Industrial', 873071);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (35, 'Legacy', 'Grocery', 391087);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (36, 'Quest', 'Clothing', 779265);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (37, 'New Yorker', 'Automotive', 48287);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (38, 'Ascender', 'Computers', 789813);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (39, 'Suburban 1500', 'Games', 256068);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (40, 'Park Avenue', 'Automotive', 404017);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (41, 'Sierra 1500', 'Garden', 383855);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (42, 'A8', 'Shoes', 430749);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (43, 'Topaz', 'Health', 81165);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (44, 'Sentra', 'Baby', 523506);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (45, 'Odyssey', 'Health', 31169);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (46, 'GL-Class', 'Music', 855116);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (47, 'S4', 'Books', 172206);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (48, 'Express 2500', 'Music', 850812);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (49, 'Mazda6', 'Electronics', 988782);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (50, '3500', 'Electronics', 382441);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (51, 'Traverse', 'Kids', 330839);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (52, 'Intrepid', 'Movies', 264517);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (53, '9-3', 'Books', 236309);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (54, 'G', 'Toys', 223018);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (55, '300ZX', 'Toys', 727379);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (56, 'Contour', 'Health', 702889);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (57, 'Grand Vitara', 'Toys', 703844);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (58, 'New Beetle', 'Baby', 464555);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (59, 'Econoline E250', 'Industrial', 231056);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (60, 'Ranger', 'Garden', 471421);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (61, 'Suburban 2500', 'Toys', 180832);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (62, 'Safari', 'Movies', 613591);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (63, 'Sorento', 'Electronics', 181367);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (64, 'C70', 'Industrial', 286244);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (65, 'ES', 'Games', 473449);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (66, 'Cabriolet', 'Games', 753801);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (67, 'Fusion', 'Industrial', 668125);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (68, 'Festiva', 'Movies', 687542);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (69, 'SC', 'Health', 421190);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (70, 'NSX', 'Jewelery', 56985);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (71, 'Rogue', 'Home', 181162);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (72, 'Grand Marquis', 'Garden', 308014);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (73, 'Mountaineer', 'Toys', 328774);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (74, 'Focus', 'Automotive', 905902);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (75, 'Versa', 'Baby', 353695);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (76, 'Canyon', 'Health', 603729);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (77, 'Challenger', 'Industrial', 945985);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (78, 'Z4', 'Tools', 776843);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (79, '400SE', 'Computers', 786879);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (80, 'Continental', 'Outdoors', 191006);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (81, 'Yukon XL 1500', 'Outdoors', 712441);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (82, 'Caravan', 'Automotive', 661873);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (83, 'Sonata', 'Jewelery', 961861);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (84, 'Envoy XUV', 'Games', 153192);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (85, 'Altima', 'Toys', 372663);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (86, 'Metro', 'Games', 280374);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (87, 'Laser', 'Tools', 84455);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (88, 'Solara', 'Movies', 923328);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (89, 'Ram Van B150', 'Garden', 263650);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (90, 'TT', 'Toys', 543192);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (91, 'Pilot', 'Sports', 332359);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (92, 'Insight', 'Books', 974519);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (93, 'S4', 'Grocery', 817263);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (94, 'LR2', 'Industrial', 588542);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (95, 'Sable', 'Health', 687095);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (96, 'Galant', 'Kids', 328994);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (97, 'Grand Voyager', 'Automotive', 877579);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (98, 'Tucson', 'Jewelery', 302557);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (99, 'Mountaineer', 'Kids', 892102);
insert into data_barang (id_barang, nama_barang, kategori, harga) values (100, '6 Series', 'Computers', 941226);
